name = "gledge"
version = "0.1.0"

description = "A Gleam library for creating Factory+ edge drivers."
licences = ["MIT"]
repository = { type = "github", user = "KavanPrice", repo = "gledge" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
